remove generate keystore from python scripts

diff --git a/templates/default/ca-keystore.sh.erb b/templates/default/ca-keystore.sh.erb
--- a/templates/default/ca-keystore.sh.erb
+++ b/templates/default/ca-keystore.sh.erb
@@ -1,9 +1,15 @@
 #!/bin/bash
 set -e
+if [ $# -ne 1 ]; then
+ echo "incorrect usage - keystore password required"
+ exit 2
+fi
+
 cd <%= node['hopssite']['certs_dir'] %>
 
+KEYSTOREPW=$1
+
 if [ -e "ca_pub.pem" ] && [ -e "priv.key" ] && [ -e "pub.pem" ] ; then
-	KEYSTOREPW=<%= @keystorepass %>
 
 	openssl pkcs12 -export -in pub.pem -inkey priv.key -out cert_and_key.p12 -name <%= node['hostname'] %> -CAfile ca_pub.pem -caname root -password pass:$KEYSTOREPW
 	keytool -importkeystore -destkeystore keystore.jks -srckeystore cert_and_key.p12 -srcstoretype PKCS12 -alias <%= node['hostname'] %> -srcstorepass $KEYSTOREPW -deststorepass $KEYSTOREPW -destkeypass $KEYSTOREPW
