add variables for hopsfs

diff --git a/templates/default/dbt.sh.erb b/templates/default/dbt.sh.erb
--- a/templates/default/dbt.sh.erb
+++ b/templates/default/dbt.sh.erb
@@ -2,42 +2,49 @@
 
 # This script allows Hopsworks to start/kill container for performing dbt jobs.
 # This script can be run by hopsworks (running as user 'glassfish') as a sudo command whereupon
-#
 
-# $0 is the file name
 help() {
     echo ""
-    echo "usage: $0 [start dbt_home_directory]"
-    echo ""
+    echo "usage: $0 [start DBT_HOME CERTS_DIR HADOOP_USERNAME EXECUTION_ID PROJECT_ID]"
     echo ""
     exit 1
 }
 
-DOMAINS_DIR=<%= node['glassfish']['domains_dir'] %>
-DBT_USER=<%= node['hops']['yarnapp']['user'] %>
-DBT_GROUP=<%= node['hops']['group'] %>
-HOPSWORKS_USER=<%= node['hopsworks']['user'] %>
+DOMAINS_DIR=/srv/hops/domains
+#DOMAINS_DIR=<%= node['glassfish']['domains_dir'] %>
+#DBT_USER=<%= node['hops']['yarnapp']['user'] %>
+#DBT_GROUP=<%= node['hops']['group'] %>
+#HOPSWORKS_USER=<%= node['hopsworks']['user'] %>
 VALID_IMAGE_NAME='<%= node['conda']['docker']['image-validation-regex'] %>'
 
 
-if [ $# -ne 2 ]; then
-  help
-fi
-
 if [ "$1" == "start" ] ; then
+ if [ $# -ne 6 ]; then
+   help
+ fi
+
   DBT_HOME=$2
-#  echo "DBT_HOME dir: ${DBT_HOME}"
-  if [! -d "${DBT_HOME}"]; then
+  CERTS_DIR=$3
+  HADOOP_USERNAME=$4
+  EXECUTION_ID=$5
+  PROJECT_ID=$6
+
+  if [ ! -d "${DBT_HOME}" ]; then
     echo "Invalid DBT_HOME directory: ${DBT_HOME}"
           exit 2
   fi
 
+  if [ ! -d "${CERTS_DIR}" ]; then
+    echo "Invalid CERTS_DIR directory: ${CERTS_DIR}"
+          exit 3
+  fi
+
 #  chmod 0730 "$DBT_HOME"
-  chown -R "${DBT_USER}":"${DBT_GROUP}" "${DBT_HOME}"
+#  chown -R "${DBT_USER}":"${DBT_GROUP}" "${DBT_HOME}"
   chmod -R 770 "${DBT_HOME}"
 
   echo "run dbt-container-launch.sh"
-  ${DOMAINS_DIR}/domain1/bin/dbt-container-launch.sh "${DBT_HOME}"
+  ${DOMAINS_DIR}/domain1/bin/dbt-container-launch.sh "${DBT_HOME}" "${CERTS_DIR}" "${HADOOP_USERNAME}" "${EXECUTION_ID}" "${PROJECT_ID}"
 fi
 
 
