HOPSWORKS-162 - Jupyter UI for Tensorflow (#80)
* store jupyter notebook settings, make private_local_dir under staging_dir for python kernel notebooks

* update jupyter tables

* fix column

* advanced col added to jupyter_settings

* new table to store livyInterpreter<->JupyterNotebooks mappings

* dont check the private_dir param

* fix permissions

* secure private dirs done, clean kill jupyter dirs

* jupyter install kernel an attr now

* jupyter/python now a variable in Hopsworks

* kagent-chef moved to hopshadoop

diff --git a/templates/default/jupyter.sh.erb b/templates/default/jupyter.sh.erb
--- a/templates/default/jupyter.sh.erb
+++ b/templates/default/jupyter.sh.erb
@@ -8,7 +8,7 @@
 
 help() {
     echo ""
-    echo "usage: $0 [start jupyter_home hadoop_home java_home anaconda_env port logfile] | [kill jupyter_home pid port] | [stop hdfs_user] | [ping pid]"
+    echo "usage: $0 [start jupyter_home hadoop_home java_home anaconda_env port logfile secret_dir] | [kill jupyter_home pid port] | [stop hdfs_user] | [ping pid]"
     echo ""
     exit 1
 }
@@ -59,11 +59,11 @@ elif [ "$1" == "kill" ] ; then
      
 
     # Remove all the directories in the home jupyter folder for this project-user.
-    sudo rm -rf ${2}/*
+    sudo rm -rf ${2}/../*
     
 elif [ "$1" == "start" ] ; then
 
-    if [ $# -ne 7 ]; then
+    if [ $# -ne 8 ]; then
 	help
     fi
 
@@ -107,11 +107,28 @@ elif [ "$1" == "start" ] ; then
 	exit 4
     fi
 
+#    if [[ $8 =~ ^\/$|(^(?=\/)|^\.|^\.\.)(\/(?=[^/\0])[^/\0]+)*\/?$ ]] ; then
+#	echo "secret_dir looks like a path has, ok"
+#    else
+#	echo "Invalid secret_dir parameter, doesn't look like a path: $8"
+#	exit 4
+#    fi
+
+     sudo mkdir -p $8
+     sudo chown -R <%= node['jupyter']['user'] %>:<%= node['jupyter']['group'] %> $8
+
+     #if [ ! -d $8 ] ; then
+     #  echo "Couldn't find data_dir: $8"
+     #  exit 1
+     #fi
+
+
+    
     # Make the group of the files, the jupyter group so that they can write to the files
     chgrp -R <%= node["jupyter"]["group"] %> $2
 
     # Launch the jupyter notebook
-    su <%= node["jupyter"]["user"] %> -c "<%= node['glassfish']['domains_dir'] %>/domain1/bin/jupyter-launch.sh $2 $3 $4 $5 $6 $7"
+    su <%= node["jupyter"]["user"] %> -c "<%= node['glassfish']['domains_dir'] %>/domain1/bin/jupyter-launch.sh $2 $3 $4 $5 $6 $7 $8"
 
 elif [ "$1" == "ping" ] ; then
     if [ $# -ne 2 ]; then
