new table to store livyInterpreter<->JupyterNotebooks mappings

diff --git a/templates/default/jupyter-launch.sh.erb b/templates/default/jupyter-launch.sh.erb
--- a/templates/default/jupyter-launch.sh.erb
+++ b/templates/default/jupyter-launch.sh.erb
@@ -35,7 +35,7 @@ fi
 
 
 export JUPYTER_DATA_DIR=$JUPYTER_HOME
-#export JUPYTER_DATA_DIR=$SECRET_DIR
+export PDIR=$SECRET_DIR
 export JUPYTER_PATH=$JUPYTER_HOME
 export JUPYTER_CONFIG_DIR=${JUPYTER_HOME}/conf
 export JUPYTER_RUNTIME_DIR=${JUPYTER_HOME}/run
@@ -59,14 +59,17 @@ if [ -f $PID_FILE ] ; then
 fi
 
 mkdir -p $SECRET_DIR
+
+if [ ! -d $SECRET_DIR ] ; then
+ echo "Couldn't find data_dir: $SECRET_DIR"
+ exit 1
+fi
+
 cd $SECRET_DIR
 
 # setsid works, and 'nohup' doesnt work as nohup processes cant write their stderr/stdout to the logfile 
 setsid jupyter notebook --debug --NotebookApp.port=$PORT </dev/zero &> $LOGFILE  &
-#  --NotebookApp.hdfsuser=$HDFS_USER
-
 echo $! > $PID_FILE
-
 
 # Check that the token is written to the logfile, return when we see it.
 token=0
