kill jupyter server properly

diff --git a/templates/default/jupyter.sh.erb b/templates/default/jupyter.sh.erb
--- a/templates/default/jupyter.sh.erb
+++ b/templates/default/jupyter.sh.erb
@@ -29,10 +29,10 @@ if [ "$1" == "kill" ] ; then
     fi
 
     # Sanity checks for injection attacks
-    if [ ! -d "$2" ] ; then
-	echo "Invalid JUPYTER_HOME directory: $2"
-	exit 1
-    fi
+    #    if [ ! -d "$2" ] ; then
+    #	echo "Invalid JUPYTER_HOME directory: $2"
+    #	exit 1
+    #    fi
 
     # Check that the port is an int (and not some injection attack)
     re='^[0-9]+$'
@@ -47,12 +47,12 @@ if [ "$1" == "kill" ] ; then
       help
     fi
 
-     
     su ${JUPYTER_USER} -c "${DOMAINS_DIR}/domain1/bin/jupyter-kill.sh $2 $3 $4"
-     
 
     # Remove all the directories in the home jupyter folder for this project-user.
-    sudo rm -rf ${2}/../*
+    if [ "$2" != "" ] ; then
+	sudo rm -rf ${2}/../*
+    fi
     
 elif [ "$1" == "start" ] ; then
 
