HOPSWORKS-382 (#142)
* flyway support added

* flyway version fix

* fix syntax

* flyway fix

* move flyway to domain1 dir

* flyway the highway

* fix versions

* fixer

* updating flyway sql names

* fix flyway sql names

* versioning hopsworks apps

* updates

* fix initial tables

* tf serving updates

* cleanup script

* trap for jupyter-launch doesnt work

* rollback recipe, returns you to the previous hopsworks version

* upgrade attr

* Cleanup (#135)

* Remove consent data and refactor auditing system

* umask column to jupyter settings

* rename roles table to host_services, roles_audit to service_status

* kagent dep - flyway

* fix context root for hopsworks-ca app

* service_status renamed to service_audit

* remove workflow tables

* group is a keyword in sql -doh

* update Berksfiles

* first-time-login setting

* set defaults for jupyter_settings

* conda search fix

* num_active_projects

* remove views

* rename services_audit to roles_audit

* account_audit and roles_audit fix

* fix sql for accounts_audit

* user_group fixes

* ldap conflict

* fix account type and status for admin, kagen users

* juypter_settings not_nulls

* add authbind to install recipe

* move authbind

* authbind ubuntu

* anaconda-prepare script/button

* change flyway to master in umask

* kill jupyter server properly

* kill cleanup for jupyter.sh

* fix for cauthRealm cleanup (#141)

* rename io.hops.crealm.CustomAuthRealm back to se.kth.bbc.crealm

* back out rename of classg

* need berksfile for testing

* re-mastering berks

* back to flyway

* fix ownership of anaconda dirs

* test upgrade to 0.2.0

* testing upgrading version

* fixed syntax error

* revert 0.2.0

* masterize

* masterize

* support snapshot version of hopsworks

* flyway again

* fix ruby sub() for strings

* cleanup sql

* masterize

diff --git a/templates/default/jupyter.sh.erb b/templates/default/jupyter.sh.erb
--- a/templates/default/jupyter.sh.erb
+++ b/templates/default/jupyter.sh.erb
@@ -8,7 +8,7 @@
 
 help() {
     echo ""
-    echo "usage: $0 [start jupyter_home hadoop_home java_home anaconda_env port logfile secret_dir] | [kill jupyter_home pid port] | [ping pid] | [list] | [killhard pid] [kernel-add jupyter_home  project_user] [kernel-remove project_user]"
+    echo "usage: $0 [start jupyter_home hadoop_home java_home anaconda_env port logfile secret_dir] | [kill jupyter_home pid port] | [ping pid] | [list] | [kernel-add jupyter_home  project_user] [kernel-remove project_user]"
     echo ""
     exit 1
 }
@@ -29,10 +29,10 @@ if [ "$1" == "kill" ] ; then
     fi
 
     # Sanity checks for injection attacks
-    if [ ! -d "$2" ] ; then
-	echo "Invalid JUPYTER_HOME directory: $2"
-	exit 1
-    fi
+    #    if [ ! -d "$2" ] ; then
+    #	echo "Invalid JUPYTER_HOME directory: $2"
+    #	exit 1
+    #    fi
 
     # Check that the port is an int (and not some injection attack)
     re='^[0-9]+$'
@@ -47,12 +47,16 @@ if [ "$1" == "kill" ] ; then
       help
     fi
 
-     
+    # Don't kill the pid from this script, as it is run with 'sudo' privileges. Only do it as user 'jupyter'
     su ${JUPYTER_USER} -c "${DOMAINS_DIR}/domain1/bin/jupyter-kill.sh $2 $3 $4"
-     
 
     # Remove all the directories in the home jupyter folder for this project-user.
-    sudo rm -rf ${2}/../*
+    if [ "$2" != "" ] ; then
+	# Try and make sure some silly directory is not deleted, that this
+	if [[ $2 = *"hops/jupyter/Projects"* ]]; then
+            sudo rm -rf ${2}/../*
+	fi
+    fi
     
 elif [ "$1" == "start" ] ; then
 
@@ -150,16 +154,7 @@ elif [ "$1" == "list" ] ; then
     # This command will output line-separated PIDs for all running jupyter-notebooks into the tmp file, from where it is read by Hopsworks
     sudo ps -ef | grep -v 'grep' | grep -i jupyter-notebook | awk '{print $2}' > /tmp/jupyterNotebookServer.pids
 
-# killhard PID    
-elif [ "$1" == "killhard" ] ; then
-    sudo ps -ef | grep -v 'grep' | grep -i jupyter-notebook | grep $2
-    if [ $? -ne 0 ] ; then
-	echo "Error killing PID: $2"
-	echo "Are you trying to kill a non jupyter-notebook process?"
-	exit 12
-    fi
-    echo "Trying to 'kill -9' jupyter notebook with PID: $2"
-    sudo kill -9 $2 2>&1 > /dev/null
+# kernel-add
 elif [ "$1" == "kernel-add" ] ; then
     if [ $# -ne 3 ]; then
 	help
