fix JAVA_HOME for jupyter

diff --git a/templates/default/jupyter.sh.erb b/templates/default/jupyter.sh.erb
--- a/templates/default/jupyter.sh.erb
+++ b/templates/default/jupyter.sh.erb
@@ -2,7 +2,7 @@
 
 help() {
     echo ""
-    echo "usage: $0 [start jupyter_home hadoop_home logfile] | [stop jupyter_home] "
+    echo "usage: $0 [start jupyter_home hadoop_home java_home logfile] | [stop jupyter_home] "
     echo ""
     exit 1
 }
@@ -22,33 +22,37 @@ if [ "$1" == "stop" ] ; then
       help
     fi
 
-    su -m <%= node["jupyter"]["user"] %> -c "./jupyter-kill.sh $2"
+    su <%= node["jupyter"]["user"] %> -c "./jupyter-kill.sh $2"
     
 elif [ "$1" == "start" ] ; then
 
-    if [ $# -ne 4 ]; then
+    if [ $# -ne 5 ]; then
 	help
     fi
 
     # Sanity checks for injection attacks
     if [ ! -d "$2" ] ; then
 	echo "Invalid JUPYTER_HOME directory: $2"
-	exit 3
+	exit 1
     fi
     if [ ! -d "$3" ] ; then
-	echo "Invalid HADOOP_HOME directory: $2"
+	echo "Invalid HADOOP_HOME directory: $3"
+	exit 2
+    fi
+    if [ ! -f "${4}/bin/java" ] ; then
+	echo "Invalid JAVA_HOME directory: $4"
 	exit 3
     fi
     # Should look like 'name-4444.log', where '4444' is the port number for the server
-    if [[ $4 =~ ^[a-zA-Z0-9]{3,255}__[a-zA-Z0-9]{3,32}\-[0-9]+\.log ]] ; then
+    if [[ $5 =~ ^[a-zA-Z0-9]{3,255}__[a-zA-Z0-9]{3,32}\-[0-9]+\.log ]] ; then
 	echo "logfile ok"
     else
-	echo "Invalid logfile parameter: $4"
+	echo "Invalid logfile parameter: $5"
 	exit 4
     fi
 
     # '-m' means preserve environment variables in process launched
-    su -m <%= node["jupyter"]["user"] %> -c "./jupyter-launch.sh $2 $3 $4"
+    su <%= node["jupyter"]["user"] %> -c "<%= node['glassfish']['domains_dir'] %>/domain1/bin/jupyter-launch.sh $2 $3 $4 $5"
 else
   help
 fi
