Revert "[HOPSWORKS-1694] run users code in docker. (#415)" (#444)
This reverts commit 5cc45e130572d63229a2b0d7b4290ad1052327a0.

diff --git a/templates/default/sklearn_serving.sh.erb b/templates/default/sklearn_serving.sh.erb
--- a/templates/default/sklearn_serving.sh.erb
+++ b/templates/default/sklearn_serving.sh.erb
@@ -7,35 +7,48 @@
 
 help() {
     echo ""
-    echo "usage: $0 [start script_name hdfs_script_path port secretdir username project_name python_path kstore_path truststore_path password_path serving_name docker_image] | [kill cid model_name project_name secretdir] "
+    echo "usage: $0 [start script_name hdfs_script_path port secretdir username project_name python_path kstore_path truststore_path password_path serving_name] | [kill pid port secretdir] "
     echo ""
     exit 1
 }
 
-SERVING_USER=<%= node['hops']['yarnapp']['user'] %>
-SERVING_GROUP=<%= node['hops']['group'] %>
+SERVING_USER=<%= node['serving']['user'] %>
+SERVING_GROUP=<%= node['serving']['group'] %>
 HOPSWORKS_USER=<%= node['hopsworks']['user'] %>
 DOMAINS_DIR=<%= node['glassfish']['domains_dir'] %>
 HADOOP_HOME=<%= node['hops']['base_dir'] %>
 
 if [ "$1" == "kill" ] ; then
 
-    if [ $# -ne 5 ]; then
+    if [ $# -ne 4 ]; then
       help
     fi
 
-    if [ ! -d "$5" ] ; then
+    # Sanity checks for injection attacks
+    re='^[0-9]+$'
+    if ! [[ $2 =~ $re ]] ; then
+      echo "error: Not a number" >&2
+      help
+    fi
+    # Check that the port is an int (and not some injection attack)
+    re='^[0-9]+$'
+     if ! [[ $3 =~ $re ]] ; then
+      echo "error: Not a number" >&2
+      help
+    fi
+
+    if [ ! -d "$4" ] ; then
       echo "Invalid SECRET_DIR directory: $4"
       exit 1
     fi
 
-    ${DOMAINS_DIR}/domain1/bin/sklearn_serving-kill.sh $2 $3 $4 $5
+    su "${SERVING_USER}" -c "${DOMAINS_DIR}/domain1/bin/sklearn_serving-kill.sh $2 $3 $4"
 
-    rm -rf "$5"
+    rm -rf "$4"
 
 elif [ "$1" == "start" ] ; then
 
-    if [ $# -ne 13 ]; then
+    if [ $# -ne 12 ]; then
       help
     fi
 
@@ -46,12 +59,6 @@ elif [ "$1" == "start" ] ; then
       help
     fi
 
-    pid=$(netstat -lntpu | grep ":$4" | awk '{print $7}')
-    if [ "$pid" != "" ] ; then
-	echo "There is already a service using this port $4"
-	exit 1
-    fi
-    
     SECRET_DIR=$5
     if [ -d "${SECRET_DIR}" ] ; then
       echo "Invalid secret directory. Directory already exists: $SECRET_DIR"
@@ -83,7 +90,7 @@ elif [ "$1" == "start" ] ; then
     fi
 
     # Launch the flask_server process as user 'serving'
-    ${DOMAINS_DIR}/domain1/bin/sklearn_serving-launch.sh $2 $4 $5 $7 $8 $6 ${12} ${13}
+    su "${SERVING_USER}" -c "${DOMAINS_DIR}/domain1/bin/sklearn_serving-launch.sh $2 $4 $5 $7 $8 $6 ${12}"
 
     if [ $? -ne 0 ] ; then
       echo "Error starting the serving server"
@@ -102,8 +109,13 @@ elif [ "$1" == "alive" ] ; then
         help
     fi
 
-    docker container list | grep -v pgrep | grep $2 | grep $3
-
+    # Sanity checks for injection attacks
+    re='^[0-9]+$'
+    if ! [[ $2 =~ $re ]] ; then
+      echo "error: Not a number" >&2
+      help
+    fi
+    su "${SERVING_USER}" -c "pgrep -f -a sklearn_flask_server | grep -v pgrep | grep $2 | grep $3"
 else
   help
 fi
diff --git a/templates/default/tensorboard.sh.erb b/templates/default/tensorboard.sh.erb
--- a/templates/default/tensorboard.sh.erb
+++ b/templates/default/tensorboard.sh.erb
@@ -7,14 +7,13 @@
 
 help() {
     echo ""
-    echo "usage: $0 [start hdfsUser hdfsLogdir tensorBoardDir port anacondaEnvironmentPath ldLibraryPath image] | [kill cid ] | [cleanup tbDir]"
+    echo "usage: $0 [start hdfsUser hdfsLogdir tensorBoardDir port anacondaEnvironmentPath hadoopVersion certsDir javaHome ldLibraryPath] | [kill pid] | [cleanup tbDir]"
     echo ""
     exit 1
 }
 
 DOMAINS_DIR=<%= node['glassfish']['domains_dir'] %>
 HADOOP_HOME=<%= node['hops']['base_dir'] %>
-TENSORBOARD_USER=<%= node['hops']['yarnapp']['user'] %>
 
 if [ "$1" == "kill" ] ; then
 
@@ -22,14 +21,30 @@ if [ "$1" == "kill" ] ; then
 	    help
     fi
     
-    echo "Killing input container_id: $2"
-    docker rm -f "$2" > /dev/null 2>&1
+    # Sanity checks for injection attacks
+    re='^[0-9]+$'
+    if ! [[ $2 =~ $re ]] ; then
+      echo "error: Not a number" >&2
+      help
+    fi
+
+    PID=$(ps aux | grep tensorboard | grep "$2")
+    if [ "$PID" != "" ] ; then
+ 	    kill -9 "$2" > /dev/null 2>&1
+    fi
+
     exit $?
-    
+
 elif [ "$1" == "start" ] ; then
 
-    if [ $# -ne 8 ]; then
+    if [ $# -ne 9 ]; then
 	help
+    fi
+
+    ls "$6"/bin/tensorboard
+    if [ $? -ne 0 ] ; then
+        echo "Could not find tensorboard binary"
+        exit 1
     fi
 
     if [ ! -d "$4" ] ; then
@@ -37,15 +52,13 @@ elif [ "$1" == "start" ] ; then
         exit 2
     fi
 
-    chown $TENSORBOARD_USER $4
-
     netstat -tulpn | grep :"$5"
     if [ $? -eq 0 ] ; then
         echo "Port is allocated already"
         exit 1
     fi
 
-    ${DOMAINS_DIR}/domain1/bin/tensorboard-launch.sh $2 $3 $4 $5 $6 $HADOOP_HOME $7 $8
+    ${DOMAINS_DIR}/domain1/bin/tensorboard-launch.sh $2 $3 $4 $5 $6 $HADOOP_HOME $7 $8 $9
 
 elif [ "$1" == "cleanup" ] ; then
 
