tf serving scripts

diff --git a/templates/default/tfserving.sh.erb b/templates/default/tfserving.sh.erb
--- a/templates/default/tfserving.sh.erb
+++ b/templates/default/tfserving.sh.erb
@@ -8,139 +8,84 @@
 
 help() {
     echo ""
-    echo "usage: $0 [start jupyter_home hadoop_home java_home anaconda_env port logfile secret_dir] | [kill jupyter_home pid port] | [ping pid] | [list] | [killhard pid] [kernel-add jupyter_home  project_user] [kernel-remove project_user]"
+    echo "usage: $0 [start model_name model_version tfserving_hdfs_dir port secret_dir enable_batching] | [kill model_name pid port secret_dir] | [ping pid] | [list] | [killhard pid]"
     echo ""
     exit 1
 }
 
 PORT=0
-CONDA_DIR=<%= node["conda"]["base_dir"] %>
-DOMAINS_DIR=<%= node['glassfish']['domains_dir'] %>
-JUPYTER_USER=<%= node['jupyter']['user'] %>
-JUPYTER_GROUP=<%= node['jupyter']['group'] %>
+TFSERVING_USER=<%= node['tfserving']['user'] %>
+TFSERVING_GROUP=<%= node['tfserving']['group'] %>
 HOPSWORKS_USER=<%= node['hopsworks']['user'] %>
-KERNELS_DIR=/usr/local/share/jupyter/kernels
-EXEC_AS_ANACONDA_USER=<%= node['conda']['user'] %>
 
 if [ "$1" == "kill" ] ; then
 
-    if [ $# -ne 4 ]; then
+    if [ $# -ne 5 ]; then
 	help
     fi
-
+    
     # Sanity checks for injection attacks
-    if [ ! -d "$2" ] ; then
-	echo "Invalid JUPYTER_HOME directory: $2"
-	exit 1
-    fi
-
-    # Check that the port is an int (and not some injection attack)
     re='^[0-9]+$'
-     if ! [[ $3 =~ $re ]] ; then
+    if ! [[ $3 =~ $re ]] ; then
       echo "error: Not a number" >&2
       help
     fi
-
+    # Check that the port is an int (and not some injection attack)
     re='^[0-9]+$'
      if ! [[ $4 =~ $re ]] ; then
       echo "error: Not a number" >&2
       help
     fi
 
+    if [ ! -d "$5" ] ; then
+	echo "Invalid SECRET_DIR directory: $5"
+	exit 1
+    fi
      
-    su ${JUPYTER_USER} -c "${DOMAINS_DIR}/domain1/bin/jupyter-kill.sh $2 $3 $4"
-     
-
-    # Remove all the directories in the home jupyter folder for this project-user.
-    sudo rm -rf ${2}/../*
+    su ${TFSERVING_USER} -c "${DOMAINS_DIR}/domain1/bin/tfserving-kill.sh $2 $3 $4 $5"
     
 elif [ "$1" == "start" ] ; then
 
-    if [ $# -ne 8 ]; then
+    if [ $# -ne 6 ]; then
 	help
     fi
 
     # Sanity checks for injection attacks
-    if [ ! -d "$2" ] ; then
-	echo "Invalid JUPYTER_HOME directory: $2"
-	exit 1
-    fi
-    if [ ! -d "$3" ] ; then
-	echo "Invalid HADOOP_HOME directory: $3"
-	exit 2
-    fi
-    if [ ! -f "${4}/bin/java" ] ; then
-	echo "Invalid JAVA_HOME directory: $4"
-	exit 3
-    fi
-
-    if [ ! -d "${5}" ] ; then
-	echo "Invalid Anaconda environment directory: $5"
-	exit 3
-    fi
-    
     re='^[0-9]+$'
-    if ! [[ $6 =~ $re ]] ; then
+    if ! [[ $5 =~ $re ]] ; then
       echo "error: Not a number" >&2
       help
     fi
-
-    pid=$(sudo ps -ef | grep jupyter-notebook | grep "port=$6" | awk '{print $2}')
-
-    if [ "$pid" != "" ] ; then
-        su vagrant -c "${DOMAINS_DIR}/domain1/bin/jupyter-kill.sh $2 $pid $6"
-	sleep 5
+    SECRET_DIR=$6
+    if [ ! -d "${SECRET_DIR}" ] ; then
+	echo "Invalid secret directory: $SECRET_DIR"
+	exit 3
     fi
-
-    # Should look like 'name-4444.log', where '4444' is the port number for the server
-    if [[ $7 =~ ^[a-zA-Z0-9_\.]{1,255}__[a-zA-Z0-9_\.]{3,32}\-[0-9]+\.log ]] ; then
-	echo "logfile ok"
-    else
-	echo "Invalid logfile parameter: $7"
-	exit 4
-    fi
-
-#    if [[ $8 =~ ^\/$|(^(?=\/)|^\.|^\.\.)(\/(?=[^/\0])[^/\0]+)*\/?$ ]] ; then
-#	echo "secret_dir looks like a path has, ok"
-#    else
-#	echo "Invalid secret_dir parameter, doesn't look like a path: $8"
-#	exit 4
-#    fi
     
-    parent=$(dirname $8)
-    sudo chown -R ${HOPSWORKS_USER}:${JUPYTER_GROUP} $parent
+    pid=$(sudo ps -ef | grep tensorflow_model_server | grep "port=$5" | awk '{print $2}')
+
+    parent=$(dirname $SECRET_DIR)
+    sudo chown -R ${HOPSWORKS_USER}:${TFSERVING_GROUP} $parent
     sudo chmod 0730 $parent
-    sudo mkdir -p $8
+    sudo mkdir -p $SECRET_DIR
     if [ $? -ne 0 ] ; then
-	echo "Error: could not create private_dir: $8"
+	echo "Error: could not create private_dir: $SECRET_DIR"
 	exit 1
     fi
-    sudo chmod -R 770 $8
-    sudo chown -R ${JUPYTER_USER}:${JUPYTER_GROUP} $8
+    sudo chmod -R 770 $SECRET_DIR
+    sudo chown -R ${TFSERVING_USER}:${TFSERVING_GROUP} $SECRET_DIR
     
-    # These files below were created by hopsworks. Change ownership now to Jupyter (if needed)
-    #    sudo chown -R ${JUPYTER_USER}:${JUPYTER_GROUP} $2
-    # Make the group of the files, the jupyter group so that they can write to the files
-    sudo chown -R ${HOPSWORKS_USER}:${JUPYTER_GROUP} $2/..
-    if [ $? -ne 0 ] ; then
-	echo "Error: could not change ownership of config_dir for Jupyter: $2"
-	exit 1
-    fi
-    sudo chmod 0730 $2/..    
-    sudo chown -R ${JUPYTER_USER}:${JUPYTER_GROUP} $2
-    sudo chmod -R 770 $2
-     
-    # Launch the jupyter notebook
-    su ${JUPYTER_USER} -c "${DOMAINS_DIR}/domain1/bin/jupyter-launch.sh $2 $3 $4 $5 $6 $7 $8"
+    # Launch the tensorflow_serving process as user 'tfserving'
+    su ${TFSERVING_USER} -c "${DOMAINS_DIR}/domain1/bin/tfserving-launch.sh $2 $3 $4 $5 $6"
 
 elif [ "$1" == "ping" ] ; then
     if [ $# -ne 2 ]; then
 	help
     fi
-    sudo ps -ef | grep -v 'grep' | grep -i jupyter-notebook | grep $2
+    sudo ps -ef | grep -v 'grep' | grep tensorflow_model_server | grep $2
     if [ $? -ne 0 ] ; then
 	echo "Error checking PID: $2"
-	echo "Are you trying to ping a non jupyter-notebook process?"
+	echo "Are you trying to ping a non tensorflow_model_server process?"
 	exit 12
     fi
     kill -0 $2
@@ -148,51 +93,18 @@ elif [ "$1" == "ping" ] ; then
 # list 
 elif [ "$1" == "list" ] ; then
     # This command will output line-separated PIDs for all running jupyter-notebooks into the tmp file, from where it is read by Hopsworks
-    sudo ps -ef | grep -v 'grep' | grep -i jupyter-notebook | awk '{print $2}' > /tmp/jupyterNotebookServer.pids
+    sudo ps -ef | grep -v 'grep' | grep -i tensorflow_model_server | awk '{print $2}' > /tmp/tensorflow_model_server.pids
 
 # killhard PID    
 elif [ "$1" == "killhard" ] ; then
-    sudo ps -ef | grep -v 'grep' | grep -i jupyter-notebook | grep $2
+    sudo ps -ef | grep -v 'grep' | grep -i tensorflow_model_server | grep $2
     if [ $? -ne 0 ] ; then
 	echo "Error killing PID: $2"
-	echo "Are you trying to kill a non jupyter-notebook process?"
+	echo "Are you trying to kill a non tensorflow_model_server process?"
 	exit 12
     fi
-    echo "Trying to 'kill -9' jupyter notebook with PID: $2"
+    echo "Trying to 'kill -9' tensorflow_model_server with PID: $2"
     sudo kill -9 $2 2>&1 > /dev/null
-elif [ "$1" == "kernel-add" ] ; then
-    if [ $# -ne 3 ]; then
-	help
-    fi
-
-# stringZ="proj__jim"
-# echo ${stringZ#*__} # prints jim
-# echo ${stringZ%__*} # prints proj
-    JUPYTER_HOME=$2
-    PROJ_USER=$3
-    PROJECT=${PROJ_USER%__*}	
-    
-    if [ ! -d /usr/local/share/jupyter/kernels/python-${PROJ_USER} ] ; then
-       sudo ${DOMAINS_DIR}/domain1/bin/jupyter-kernel-install.sh $EXEC_AS_ANACONDA_USER $PROJECT $PROJ_USER $CONDA_DIR $JUPYTER_HOME
-    fi
- 
-#   This function can remove either an individual user with the 'hdfsusername' or all users in a project with 'projectname*' 
-elif [ "$1" == "kernel-remove" ] ; then
-    if [[ $2 == *".."* ]]; then
-	echo "Injection Attack when removing python kernel with name python-$2 ?"
-	exit 99
-    fi
-    if [[ $2 == "*" ]]; then
-	echo "Injection Attack when removing python kernel with name '*' ?"
-	exit 98
-    fi
-
-    if [ ! -d "${KERNELS_DIR}/python-${2}" ] ; then
-	echo "Invalid KERNEL directory: $2"
-	exit 2
-    fi
-    
-    sudo rm -rf ${KERNELS_DIR}/python-${2}
 else
   help
 fi
