[HOPSWORKS-643] Refactor TfServing code to allow pluggable providers

diff --git a/templates/default/tfserving.sh.erb b/templates/default/tfserving.sh.erb
--- a/templates/default/tfserving.sh.erb
+++ b/templates/default/tfserving.sh.erb
@@ -8,52 +8,52 @@
 
 help() {
     echo ""
-    echo "usage: $0 [start model_name model_version tfserving_hdfs_dir port secret_dir enable_batching] | [kill model_name pid port secret_dir] | [ping pid] | [list] | [killhard pid]"
+    echo "usage: $0 [start model_name hdfs_model_path port secretdir username] | [kill pid port secretdir] | [update model_name hdfs_model_path secretdir username] "
     echo ""
     exit 1
 }
 
-TFSERVING_USER=<%= node['tfserving']['user'] %>
-TFSERVING_GROUP=<%= node['tfserving']['group'] %>
-HOPSWORKS_USER=<%= node['hopsworks']['user'] %>
-DOMAINS_DIR=<%= node['glassfish']['domains_dir'] %>
-HADOOP_HOME=<%= node['hops']['base_dir'] %>
+TFSERVING_USER=tfserving
+TFSERVING_GROUP=tfserving
+HOPSWORKS_USER=glassfish
+DOMAINS_DIR=/srv/hops/domains
+HADOOP_HOME=/srv/hops/hadoop
 
 if [ "$1" == "kill" ] ; then
 
-    if [ $# -ne 5 ]; then
+    if [ $# -ne 4 ]; then
 	help
     fi
-    
+
     # Sanity checks for injection attacks
     re='^[0-9]+$'
-    if ! [[ $3 =~ $re ]] ; then
+    if ! [[ $2 =~ $re ]] ; then
       echo "error: Not a number" >&2
       help
     fi
     # Check that the port is an int (and not some injection attack)
     re='^[0-9]+$'
-     if ! [[ $4 =~ $re ]] ; then
+     if ! [[ $3 =~ $re ]] ; then
       echo "error: Not a number" >&2
       help
     fi
 
-    if [ ! -d "$5" ] ; then
-	echo "Invalid SECRET_DIR directory: $5"
-	exit 1
+    if [ ! -d "$4" ] ; then
+      echo "Invalid SECRET_DIR directory: $4"
+      exit 1
     fi
-     
-    su "${TFSERVING_USER}" -c "${DOMAINS_DIR}/domain1/bin/tfserving-kill.sh $2 $3 $4 $5"
 
-    rm -rf "$5"
+    su "${TFSERVING_USER}" -c "${DOMAINS_DIR}/domain1/bin/tfserving-kill.sh $2 $3 $4"
+
+    rm -rf "$4"
 
 elif [ "$1" == "start" ] ; then
 
-    if [ $# -ne 7 ]; then
-	help
+    if [ $# -ne 6 ]; then
+      help
     fi
 
-    which tensorflow_model_server
+    command -v tensorflow_model_server
     if [ $? -ne 0 ] ; then
         echo "Could not find tensorflow_model_server command"
         exit 1
@@ -61,73 +61,57 @@ elif [ "$1" == "start" ] ; then
 
     # Sanity checks for injection attacks
     re='^[0-9]+$'
-    if ! [[ $5 =~ $re ]] ; then
+    if ! [[ $4 =~ $re ]] ; then
       echo "error: Not a number" >&2
       help
     fi
-    SECRET_DIR=$6
 
+    SECRET_DIR=$5
     if [ -d "${SECRET_DIR}" ] ; then
-	echo "Invalid secret directory. Directory already exists: $SECRET_DIR"
-	exit 3
-    fi
-    sudo mkdir -p "$SECRET_DIR"
-    sudo chown "$TFSERVING_USER" "$SECRET_DIR"
-    
-    pid=$(sudo ps -ef | grep tensorflow_model_server | grep "port=$5" | awk '{print $2}')
-
-    if [ "$pid" != "" ] ; then
-        su "$TFSERVING_USER" -c "${DOMAINS_DIR}/domain1/bin/tfserving-kill.sh $2 $pid $5 $6"
-	sleep 5
+      echo "Invalid secret directory. Directory already exists: $SECRET_DIR"
+      exit 3
     fi
 
-    parent=$(dirname "$SECRET_DIR")
-    sudo chown -R "${HOPSWORKS_USER}":"${TFSERVING_GROUP}" "$parent"
-    sudo chmod 0730 "$parent"
-    sudo mkdir -p "$SECRET_DIR"
+    sudo mkdir "$SECRET_DIR"
     if [ $? -ne 0 ] ; then
-	echo "Error: could not create private_dir: $SECRET_DIR"
-	exit 1
+      echo "Error: could not create private_dir: $SECRET_DIR"
+      exit 1
     fi
-    sudo chmod -R 770 "$SECRET_DIR"
+    sudo mkdir "$SECRET_DIR/$2"
+
     sudo chown -R "${TFSERVING_USER}":"${TFSERVING_GROUP}" "$SECRET_DIR"
-    
+    sudo chmod -R 770 "$SECRET_DIR"
+
+    su "${HOPSWORKS_USER}" -c "HADOOP_PROXY_USER=$6 ${HADOOP_HOME}/bin/hdfs dfs -copyToLocal $3 $SECRET_DIR/$2"
+    if [ $? -ne 0 ] ; then
+      echo "Error downloading the model on the local Fs"
+      exit 1
+    fi
+
     # Launch the tensorflow_serving process as user 'tfserving'
-    su "${TFSERVING_USER}" -c "${DOMAINS_DIR}/domain1/bin/tfserving-launch.sh $2 $3 $4 $5 $6 $7"
+    su "${TFSERVING_USER}" -c "${DOMAINS_DIR}/domain1/bin/tfserving-launch.sh $2 $4 $5"
 
-    su "${HOPSWORKS_USER}" -c "${HADOOP_HOME}/bin/hdfs dfs -copyToLocal $4/$2 $SECRET_DIR/tfserving/model"
+elif [ "$1" == "update" ] ; then
 
-elif [ "$1" == "ping" ] ; then
-    if [ $# -ne 2 ]; then
-	help
+    if [ $# -ne 5 ]; then
+      help
     fi
-    sudo ps -ef | grep -v 'grep' | grep tensorflow_model_server | grep "$2"
+    SECRET_DIR=$4
+
+    if [ ! -d "${SECRET_DIR}" ] ; then
+      echo "Invalid secret directory. Directory doesn't exists: $SECRET_DIR"
+      exit 3
+    fi
+
+    su "${HOPSWORKS_USER}" -c "HADOOP_PROXY_USER=$5 ${HADOOP_HOME}/bin/hdfs dfs -copyToLocal $3 $SECRET_DIR/$2"
+
     if [ $? -ne 0 ] ; then
-	echo "Error checking PID: $2"
-	echo "Are you trying to ping a non tensorflow_model_server process?"
-	exit 12
+      echo "Error downloading the model on the local Fs"
+      exit 1
     fi
-    kill -0 "$2"
-
-# list 
-elif [ "$1" == "list" ] ; then
-    # This command will output line-separated PIDs for all running jupyter-notebooks into the tmp file, from where it is read by Hopsworks
-    sudo ps -ef | grep -v 'grep' | grep -i tensorflow_model_server | awk '{print $2}' > /tmp/tensorflow_model_server.pids
-
-# killhard PID    
-elif [ "$1" == "killhard" ] ; then
-    sudo ps -ef | grep -v 'grep' | grep -i tensorflow_model_server | grep "$2"
-    if [ $? -ne 0 ] ; then
-	echo "Error killing PID: $2"
-	echo "Are you trying to kill a non tensorflow_model_server process?"
-	exit 12
-    fi
-    echo "Trying to 'kill -9' tensorflow_model_server with PID: $2"
-    sudo kill -9 "$2" > /dev/null 2>&1
 
 # get Logs for serving
 elif [ "$1" == "logs" ] ; then
-    HOST=$2
     LOGFILE=$3
 
     cat "${LOGFILE}"
