HOPSWORKS-265 TensorFlow Serving

diff --git a/templates/default/tfserving.sh.erb b/templates/default/tfserving.sh.erb
--- a/templates/default/tfserving.sh.erb
+++ b/templates/default/tfserving.sh.erb
@@ -50,6 +50,12 @@ elif [ "$1" == "start" ] ; then
 	help
     fi
 
+    which tensorflow_model_server
+    if [ $? -ne 0 ] ; then
+        echo "Could not find tensorflow_model_server command"
+        exit 1
+    fi
+
     # Sanity checks for injection attacks
     re='^[0-9]+$'
     if ! [[ $5 =~ $re ]] ; then
@@ -84,7 +90,7 @@ elif [ "$1" == "start" ] ; then
     sudo chown -R ${TFSERVING_USER}:${TFSERVING_GROUP} $SECRET_DIR
     
     # Launch the tensorflow_serving process as user 'tfserving'
-    su ${TFSERVING_USER} -c "${DOMAINS_DIR}/domain1/bin/tfserving-launch.sh $2 $3 $4 $5 $6"
+    su ${TFSERVING_USER} -c "${DOMAINS_DIR}/domain1/bin/tfserving-launch.sh $2 $3 $4 $5 $6 $7"
 
 elif [ "$1" == "ping" ] ; then
     if [ $# -ne 2 ]; then
@@ -113,6 +119,13 @@ elif [ "$1" == "killhard" ] ; then
     fi
     echo "Trying to 'kill -9' tensorflow_model_server with PID: $2"
     sudo kill -9 $2 2>&1 > /dev/null
+
+# get Logs for serving
+elif [ "$1" == "logs" ] ; then
+    HOST=$2
+    LOGFILE=$3
+
+    cat ${LOGFILE}
 else
   help
 fi
