fixes for unzipping

diff --git a/templates/default/unzip-hdfs-files.sh.erb b/templates/default/unzip-hdfs-files.sh.erb
--- a/templates/default/unzip-hdfs-files.sh.erb
+++ b/templates/default/unzip-hdfs-files.sh.erb
@@ -14,7 +14,7 @@ hdfsFile=$2
 HDFS_USER=$3
 
 #FSM states: STAGING, UNZIPPING, UPLOADING, CHOWNING, SUCCESS, FAILED
-fsmFile=$1/fsm.txt
+fsmFile="$(dirname $1)/fsm-$(basename $1).txt"
 
 function finish {
     rm -rf $workdir
@@ -23,9 +23,9 @@ trap finish EXIT
 
 function check_error {
     if [ $? -ne 0 ] ; then
-       echo "FAILED" > $1/fsm.txt	
+      echo "FAILED" > $fsmFile
+      exit 1	
     fi
-    exit 1
 }
 
 
@@ -38,7 +38,7 @@ check_error
 dir=$(dirname "${normalizedPath}")
 check_error
 
-filedir="${file%%.*}"
+#filedir="${file%%.*}"
 check_error
 hdfsDir=${dir}/${filedir}
 
@@ -47,11 +47,11 @@ check_error
 
 filename=$(basename "$2")
 
-echo "STAGING" > $1/fsm.txt
+echo "STAGING" > $fsmFile
 <%= node["hops"]["base_dir"] %>/bin/hdfs dfs -copyToLocal $hdfsFile $workdir
 check_error
 
-echo "UNZIPPING" > $1/fsm.txt
+echo "UNZIPPING" > $fsmFile
 
 # State Machine State Change. File now staged to local FS.
 # Java program checks if this file is written to see if this file exists:  $workdir/$(basename $hdfsfile)
@@ -69,62 +69,45 @@ check_error
 # Java program checks if this file is written to see if this directory exists:  $workdir/$(basename $hdfsfile)
 
 
-#filedir="${file%%.*}"
-#stripped=${dir}/${filedir}
+filedir="${file%%.*}"
 
-# case "$file" in 
-#   *.tar.gz)
-#      stripped=$(basename $hdfsFile .tar.gz)
-#      mkdir -p $stripped
-#      tar zxf $file -C ./$stripped
-#     ;;
-#   *.bz2)
-#      stripped=$(basename $hdfsFile .bz2)
-#      mkdir -p $stripped
-#      tar jxf $file -C ./$stripped
-#     ;;
-#   *.bzip2)
-#      stripped=$(basename $hdfsFile .bz2)
-#      mkdir -p $stripped
-#      tar jxf $file -C ./$stripped
-#     ;;
-#   *.tgz)
-#      stripped=$(basename $hdfsFile .tgz)
-#      mkdir -p $stripped
-#      tar zxf $file -C ./$stripped
-#     ;;
-#   *.gz)
-#      stripped=$(basename $hdfsFile .gz)
-#      mkdir -p $stripped
-#      gunzip -d -c $file > ./$stripped
-#     ;;
-#   *.7z)
-#      stripped=$(basename $hdfsFile .7z)
-#      mkdir -p $stripped
-#      7z x  $file  -o${stripped}
-#     ;;
-#   *.rar)
-#      stripped=$(basename $hdfsFile .rar)
-#      mkdir -p $stripped
-#      7z x  $file  -o${stripped}
-#     ;;
-#   *.zip)
-#      stripped=$(basename $hdfsFile .zip)
-#      mkdir -p $stripped
-#      unzip $file -d ./$stripped
-#     ;;
-#   *)
-#     help
-#     ;;
-# esac
+case "$file" in 
+  *.tar.gz)
+     filedir=$(basename $hdfsFile .tar.gz)
+    ;;
+  *.bz2)
+     filedir=$(basename $hdfsFile .bz2)
+    ;;
+  *.bzip2)
+     filedir=$(basename $hdfsFile .bz2)
+    ;;
+  *.tgz)
+     filedir=$(basename $hdfsFile .tgz)
+    ;;
+  *.gz)
+     filedir=$(basename $hdfsFile .gz)
+    ;;
+  *.7z)
+     filedir=$(basename $hdfsFile .7z)
+    ;;
+  *.rar)
+     filedir=$(basename $hdfsFile .rar)
+    ;;
+  *.zip)
+     filedir=$(basename $hdfsFile .zip)
+    ;;
+  *)
+    help
+    ;;
+esac
 
-echo "UPLOADING" > $1/fsm.txt
+echo "UPLOADING" > $fsmFile
 <%= node["hops"]["base_dir"] %>/bin/hdfs dfs -copyFromLocal ./$filedir $dir
 check_error
 
-echo "CHOWNING" > $1/fsm.txt
+echo "CHOWNING" > $fsmFile
 <%= node["hops"]["base_dir"] %>/bin/hdfs dfs -chown -R ${HDFS_USER} $hdfsDir
 check_error
 
-echo "SUCCESS" > $1/fsm.txt
+echo "SUCCESS" > $fsmFile
 
