add a FSM for unzipping in a file that can be read from the java program

diff --git a/templates/default/unzip-hdfs-files.sh.erb b/templates/default/unzip-hdfs-files.sh.erb
--- a/templates/default/unzip-hdfs-files.sh.erb
+++ b/templates/default/unzip-hdfs-files.sh.erb
@@ -1,7 +1,5 @@
 #!/bin/bash
 
-set -e
-
 help() {
   echo "usage: $0 localWorkdir srcFileInHdfs HDFS_USER"
   exit 1
@@ -15,39 +13,45 @@ workdir=$1
 hdfsFile=$2
 HDFS_USER=$3
 
-prefix='hdfs://'
-normalizedPath=${hdfsFile#${prefix}}
+#FSM states: STAGING, UNZIPPING, UPLOADING, CHOWNING, SUCCESS, FAILED
+fsmFile=$1/fsm.txt
 
-file=$(basename $normalizedPath)
-dir=$(dirname "${normalizedPath}")
+function finish {
+    rm -rf $workdir
+}
+trap finish EXIT
 
-filedir="${file%%.*}"
-hdfsDir=${dir}/${filedir}
-
-cleanup() {
-   cd $workdir
-   rm $file
-   rm -rf ./$filedir
+function check_error {
+    if [ $? -ne 0 ] ; then
+       echo "FAILED" > $1/fsm.txt	
+    fi
+    exit 1
 }
 
 
+prefix='hdfs://'
+normalizedPath=${hdfsFile#${prefix}}
+check_error
+
+file=$(basename $normalizedPath)
+check_error
+dir=$(dirname "${normalizedPath}")
+check_error
+
+filedir="${file%%.*}"
+check_error
+hdfsDir=${dir}/${filedir}
+
 cd $workdir
-freespace=`df $PWD | awk '/[0-9]%/{print $(NF-2)}'`
-freespace=$(($freespace * 1000))
+check_error
 
-filesize=`/srv/hops/hadoop/bin/hadoop fs -du -s $hdfsFile | awk  '{print $1}'`
-# Amount of space needed to download and decompress the file
-filesize=$(($filesize * 3))
+filename=$(basename "$2")
 
-if [ $filesize -gt $freespace ] ; then
-  echo "Not enough free space on the local harddisk"
-  exit 2
-fi  
-
-
-#zips=$(hadoop fs -ls /yourpath/*.zip | awk '{print $8}')
-
+echo "STAGING" > $1/fsm.txt
 <%= node["hops"]["base_dir"] %>/bin/hdfs dfs -copyToLocal $hdfsFile $workdir
+check_error
+
+echo "UNZIPPING" > $1/fsm.txt
 
 # State Machine State Change. File now staged to local FS.
 # Java program checks if this file is written to see if this file exists:  $workdir/$(basename $hdfsfile)
@@ -59,6 +63,7 @@ fi
 
 cd $workdir
 dtrx -o -n $file
+check_error
 
 # State Machine State Change. File now extracted to local FS.
 # Java program checks if this file is written to see if this directory exists:  $workdir/$(basename $hdfsfile)
@@ -113,20 +118,13 @@ dtrx -o -n $file
 #     ;;
 # esac
 
+echo "UPLOADING" > $1/fsm.txt
 <%= node["hops"]["base_dir"] %>/bin/hdfs dfs -copyFromLocal ./$filedir $dir
+check_error
+
+echo "CHOWNING" > $1/fsm.txt
 <%= node["hops"]["base_dir"] %>/bin/hdfs dfs -chown -R ${HDFS_USER} $hdfsDir
+check_error
 
-# State Machine State Change. File now copied to HDFS.
-# Java program checks if this file is written to see if this directory exists:  /Projects/PROJ/Dataset/$(basename $hdfsfile)
+echo "SUCCESS" > $1/fsm.txt
 
-#   rm -rf ./$stripped
-
-# State Machine State Change. File is now cleaned up from local staging directory
-# Java program checks if this file is written to see if this directory does not exist
-
-   
-echo "Done copying from $file to $dir"
-
-cleanup
-
-echo "Done cleaning up"
